module.exports =
{
  "WIDTH": 4000,
  "HEIGHT": 4000,
  "MODE": "tdmGrowth",
  "RANDOM_COLORS": true, 
  "ALLOW_SERVER_END": true,
"ROOM_SETUP": [
["bas2", "bas2", "bas2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm","norm", "norm", "norm", "norm", "bas1", "bas1", "bas1"],
   ["bas2", "bap2", "bas2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid","norm", "norm", "norm", "norm", "bas1", "bap1", "bas1"],
   ["bas2", "bas2", "bas2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm","norm", "rock", "norm", "norm", "bas1", "bas1", "bas1"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "rock", "norm","norm", "norm", "roid", "norm", "norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "norm","norm", "rock", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "roid", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "roid", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "rock"],
   ["roid", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["rock", "norm", "norm", "rock", "norm", "norm", "nest", "nest", "wall", "edge", "wall", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "edge", "domx", "edge", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "roid", "norm", "norm", "rock", "norm", "nest", "nest", "wall", "edge", "wall", "nest", "nest", "norm", "norm", "norm", "rock","rock", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "rock", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
   ["norm", "roid", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid","rock", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid", "rock", "norm", "norm", "roid", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "roid", "rock", "norm", "roid", "norm", "rock", "norm","norm", "norm", "norm"],
   ["bas3", "bas3", "bas3", "norm", "norm", "norm", "rock", "norm", "norm", "rock", "norm", "norm", "norm", "norm", "norm", "norm","bas4", "bas4", "bas4"],
   ["bas3", "bap3", "bas3", "norm", "norm", "roid", "norm", "rock", "norm", "norm", "norm", "rock","rock", "norm", "norm", "norm", "bas4", "bap4", "bas4"],
   ["bas3", "bas3", "bas3", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm","bas4", "bas4", "bas4"]
  ],
  "SKILL_CAP": 275,
  "FOOD_AMOUNT": 1, 
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [1, 2, 3, 4],
  "BOTS": 10,
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [1, 2, 3, 4],
  "BASE_DRONES": true,
  "GROWTH": true,
  "SPAWN_FOOD": true,
  "SPAWN_NEUTRAL_BOSSES": true,
  "SPAWN_CRASHER": true,
  "SPAWN_SENTINEL": true,
}
