module.exports = {
  WIDTH: 2000,
  HEIGHT: 2000,
  MODE: "biome",
  ALLOW_SERVER_END: true,
  ROOM_SETUP: [
["bas1", "sri1", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
["sri1", "sri1", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm"],
["norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm"],
["norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm"],
["norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm"],
["norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm"],
["norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm"],
["norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "vpr0", "sri4"],
["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "sri4", "bas4"]
],
  FOOD_AMOUNT: 1,
  PLAYER_SPAWN_LOCATION: "bas",
  CONSIDER_PLAYER_TEAM_LOCATION: true,
  TEAMS: [4],
  BOTS: 10,
  BOT_SPAWN_LOCATION: "bas",
  CONSIDER_BOT_TEAM_LOCATION: true,
  BOT_TEAMS: [1],
  BASE_DRONES: true,
  SPAWN_FOOD: true,
  SPAWN_NEUTRAL_BOSSES: true,
  SPAWN_CRASHER: true,
  SPAWN_SENTINEL: true,
  SPAWN_VOIDLORD_ENEMIES: true,
};
