 
module.exports =
{ 
  "WIDTH": 5000, 
  "HEIGHT": 5000,
  "MODE": "Faction Madness",
  "ALLOW_SERVER_END": true,
"ROOM_SETUP": [ 
   ["bas2", "bas2", "bas2", "frt2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "dom3", "bas3", "bas3", "bas3"],
   ["bas2", "bas2", "bas2", "gte2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "gte3", "bas3", "bas3", "bas3"],
   ["bas2", "bas2", "bas2", "frt2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "frt3", "dom3", "bas3", "bas3"],
   ["frt2", "gte2", "frt2", "af12", "norm", "voip", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "voip", "norm", "dom3", "frt3", "gte3", "dom3"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "voip", "norm", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "wall", "nest", "wall", "nest", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "domx", "norm", "nest", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "wall", "nest", "wall", "nest", "norm", "norm", "norm", "norm","norm",  "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "voip","norm", "norm", "norm"],
   ["frt1", "gte1", "frt1", "af11", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "af14","bas4", "gte4", "bas4"],
   ["bas1", "bas1", "bas1", "frt1", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bas4","bas4", "bas4", "bas4"],
   ["bas1", "bas1", "bas1", "gte1", "norm", "norm", "voip", "norm", "norm", "norm", "norm", "voip", "norm", "norm", "norm", "gte4","bas4", "bas4", "bas4"],
   ["dom1", "bas1", "bas1", "frt1", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bas4","bas4", "bas4", "dome"]
  ],
  "FOOD_AMOUNT": 1, 
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [1, 2, 3, 4],
  "BOTS": 10,
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [1, 2, 3, 4],
  "BASE_DRONES": true,
  "SPAWN_FOOD": true,
  "SPAWN_NEUTRAL_BOSSES": true,
  "SPAWN_CRASHER": true,
  "SPAWN_SENTINEL": true,
  "SPAWN_GUARDIAN_BOSSES": true,
  "SPAWN_FALLEN_BOSSES": true,
  "SPAWN_PENTAGON_SENTINELS": true,
  "SPAWN_VOIDLORD_ENEMIES": true,
}
