

module.exports = {
  "WIDTH": 3600,
  "HEIGHT": 3600,
  "MODE": "4TeamSoccer",
  "goals": 10,
"ROOM_SETUP": [
["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"],
["wall", "wall", "wall", "wall", "bas3", "bas3", "bas3", "bas3", "bas3", "wall", "wall", "wall", "wall"],
["wall", "wall", "wall", "wall", "bas3", "bas3", "bas3", "bas3", "bas3", "wall", "wall", "wall", "wall"],
["wall", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "wall", "wall"],
["wall", "bas1", "bas1", "norm", "norm", "norm", "none", "norm", "norm", "norm", "bas2", "bas2", "wall"],
["wall", "bas1", "bas1", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bas2", "bas2", "wall"],
["wall", "bas1", "bas1", "norm", "norm", "norm", "ball", "norm", "norm", "norm", "bas2", "bas2", "wall"],
["wall", "bas1", "bas1", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bas2", "bas2", "wall"],
["wall", "bas1", "bas1", "norm", "norm", "norm", "none", "norm", "norm", "norm", "bas2", "bas2", "wall"],
["wall", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "wall", "wall"],
["wall", "wall", "wall", "wall", "bas4", "bas4", "bas4", "bas4", "bas4", "wall", "wall", "wall", "wall"],
["wall", "wall", "wall", "wall", "bas4", "bas4", "bas4", "bas4", "bas4", "wall", "wall", "wall", "wall"],
["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"]
],
  "DEADLY_BORDERS": true,
  "BOTS": 15,
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [1, 2, 3, 4],
  "TEAMS": [1, 2, 3, 4],
  "SOCCER": true,
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false,
}
