module.exports = {
  WIDTH: 7500,
  HEIGHT: 7500,
  MODE: "tdm",
  ALLOW_SERVER_END: true,
  ROOM_SETUP: [
    ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "norm", "port", "port", "port", "port", "port", "port", "port", "frt4", "port", "port", "port", "port", "port", "bas4","bas4", "bas4", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "norm", "norm", "port", "port", "port", "port", "port", "frt4", "frt4", "port", "port", "port", "port", "port", "port","bas4", "bas4", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "norm", "port", "port", "port", "port", "port", "frt4", "frt4", "port", "port", "port", "port", "port", "port", "port","port", "bas4", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "port", "norm", "port", "port", "frt4", "gte4", "frt4", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "port", "port", "port", "frt4", "frt4", "port", "frt4", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "frt4", "gte4", "frt4", "port", "port", "frt4", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "norm", "port", "port", "port", "port", "frt4", "frt4", "frt4", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "port", "port", "port", "port", "port", "port", "port", "frt4", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "frt3", "gte3", "gte3", "frt3", "frt3", "frt3", "frt3", "frt3", "frt3", "frt3", "frt3", "frt3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "port", "port", "port", "port", "port", "port", "port", "frt4", "frt4", "gte4", "frt4", "port", "port", "port","port", "port", "wall"],
    ["wall", "bas3", "bas3", "bas3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "norm", "norm", "port", "port", "port", "port", "port", "port", "frt4", "port", "port", "gte4", "port", "port", "port","port", "port", "wall"],
    ["wall", "bas3", "bas3", "bas3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "port", "norm", "port", "port", "port", "port", "port", "port", "frt4", "port", "port", "frt4", "frt4", "frt4", "frt4","port", "port", "wall"],
    ["wall", "bas3", "bas3", "bas3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "norm", "port", "port", "port", "port", "port", "port", "frt4", "frt4", "port", "port", "port", "port", "port", "frt4","port", "port", "wall"],
    ["wall", "bas3", "bas3", "bas3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "port", "port", "norm", "port", "port", "port", "port", "gte4", "port", "port", "port", "port", "port", "port", "frt4","gte4", "frt4", "wall"],
    ["wall", "bas3", "bas3", "bas3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "norm", "port", "port", "port", "port", "frt4", "frt4", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "bas3", "bas3", "bas3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "norm", "port", "port", "port", "port", "frt4", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "bas3", "bas3", "bas3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "frt3", "frt3","norm", "norm", "norm", "norm", "frt4", "port", "port", "port", "frt4", "gte4", "frt4", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "frt3", "gte3", "gte3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "dom3", "ftD3", "ftD3", "dom3","norm", "norm", "norm", "norm", "frt4", "norm", "norm", "port", "frt4", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "gte3", "gte3", "norm","norm", "norm", "norm", "norm", "frt4", "port", "port", "frt4", "frt4", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "fao3", "fao3", "norm","norm", "norm", "norm", "norm", "norm", "frt4", "frt4", "frt4", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "fao3", "fao3", "norm","norm", "norm", "norm", "norm", "norm", "frt4", "port", "frt4", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "gte3", "gte3", "norm","norm", "norm", "norm", "norm", "norm", "frt4", "port", "frt4", "frt4", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "dom3", "ftU3", "ftU3", "dom3","norm", "norm", "norm", "norm", "norm", "frt4", "norm", "port", "gte4", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "frt3", "frt3","norm", "norm", "norm", "norm", "norm", "frt4", "port", "port", "frt4", "frt4", "port", "port", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "norm", "frt4", "norm", "port", "port", "frt4", "gte4", "frt4", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "norm", "norm", "port", "port", "port", "port", "gte4", "port", "port", "port", "port", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "port", "port", "port", "port", "port", "port", "gte4", "port", "port", "port", "port", "port", "port", "frt4","gte4", "frt4", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "norm", "port", "port", "port", "port", "port", "frt4", "frt4", "port", "port", "port", "frt4", "gte4", "frt4","port", "port", "wall"],
    ["wall", "frt3", "frt3", "gte3", "gte3", "frt3", "frt3", "frt3", "gte3", "gte3", "frt3", "frt3", "frt3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "port", "norm", "port", "port", "port", "port", "port", "frt4", "port", "port", "port", "frt4", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "norm", "port", "norm", "port", "port", "port", "port", "frt4", "frt4", "port", "port", "gte4", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "port", "norm", "norm", "port", "port", "port", "port", "port", "frt4", "frt4", "frt4", "frt4", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "norm", "frt4", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port", "frt4", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "port", "norm", "port", "port", "port", "port", "port", "port", "port", "port", "port", "frt4", "port", "port", "port","port", "port", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "port", "port", "port", "port", "port", "port", "port", "port", "port", "port", "frt4", "frt4", "port", "port", "port","port", "bas4", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "norm", "port", "port", "port", "port", "port", "port", "port", "frt4", "gte4", "frt4", "port", "port", "port", "port","bas4", "bas4", "wall"],
    ["wall", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "spw3", "spw3", "spw3", "spw3", "spw3", "spw3", "frt3", "frt3", "norm","norm", "norm", "norm", "frt4", "port", "port", "norm", "port", "port", "port", "port", "port", "frt4", "port", "port", "port", "port", "port", "bas4","bas4", "bas4", "wall"],
    ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall"]
    ],
  FOOD_AMOUNT: 0.1,
  PLAYER_SPAWN_LOCATION: "bas",
  CONSIDER_PLAYER_TEAM_LOCATION: true,
  TEAMS: [3, 4],
  BOTS: 10,
  BOT_SPAWN_LOCATION: "bas",
  CONSIDER_BOT_TEAM_LOCATION: true,
  BOT_TEAMS: [3, 4],
  BASE_DRONES: true,
  SPAWN_FOOD: true,
  SPAWN_NEUTRAL_BOSSES: true,
  SPAWN_CRASHER: true,
  SPAWN_SENTINEL: true,
  SPAWN_FALLEN_ENEMIES: true,
  SPAWN_VOIDLORD_ENEMIES: true,
};
