
module.exports =
{
  "WIDTH": 5000,
  "HEIGHT": 5000,
  "MODE": "JJ's RF",
  "RANDOM_COLORS": true,
  "ROOM_SETUP":[
    ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"],//24
    ["wall", "tst0", "tst0", "tst1", "tst1", "wall", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall"],
    ["wall", "bas1", "bas1", "bas1", "bas1", "wall", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall"],
    ["wall", "bas1", "bas1", "bas1", "bas1", "wall", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall"],
    ["wall", "tst0", "bas1", "bas1", "tst1", "wall", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall"],
    ["wall", "tst0", "bas1", "bas1", "tst1", "wall", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall"],
    ["wall", "tst0", "bas1", "bas1", "tst1", "wall", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "bos1", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall"],
    ["wall", "wall", "gte1", "gte1", "wall", "wall", "wall", "wall", "wall", "wall", "gte1", "gte1", "wall", "wall", "wall", "wall", "wall", "gte1", "gte1", "wall", "wall", "wall", "wall", "wall"],
    ["wall", "bad1", "bas1", "bas1", "bas1", "gte1", "bas1", "dom0", "dom0", "bas1", "bas1", "bas1", "wall", "paf0", "wall", "fao0", "bos5", "gte1", "bas1", "wall", "tst2", "bas1", "tst5", "wall"],
    ["wall", "bas1", "bas1", "bas1", "bas1", "gte1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "wall", "bos5", "wall", "fao0", "bos5", "gte1", "bas1", "wall", "tst2", "bas1", "tst5", "wall"],
    ["wall", "spw1", "bas1", "bas1", "bas1", "wall", "bas1", "dom0", "dom0", "bas1", "bas1", "bad1", "wall", "gte1", "wall", "wall", "wall", "wall", "bad1", "wall", "tst2", "bas1", "tst5", "wall"],
    ["wall", "spw1", "bas1", "bas1", "bas1", "wall", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "gte1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "tst5", "wall"],
    ["wall", "spw1", "bas1", "bas1", "bas1", "wall", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "gte1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "tst5", "wall"],
    ["wall", "spw1", "bas1", "bas1", "bas1", "wall", "bas1", "dom0", "dom0", "bas1", "bas1", "bad1", "wall", "gte1", "wall", "wall", "wall", "wall", "bad1", "wall", "tst2", "bas1", "tst5", "wall"],
    ["wall", "bas1", "bas1", "bas1", "bas1", "gte1", "bas1", "bas1", "bas1", "bas1", "bas1", "bas1", "wall", "bos5", "wall", "ftR0", "bos5", "gte1", "bas1", "wall", "tst2", "bas1", "tst5", "wall"],
    ["wall", "bad1", "bas1", "bas1", "bas1", "gte1", "bas1", "dom0", "dom0", "bas1", "bas1", "bas1", "wall", "fta0", "wall", "ftR0", "bos5", "gte1", "bas1", "wall", "tst2", "bas1", "tst5", "wall"],
    ["wall", "wall", "gte1", "gte1", "wall", "wall", "wall", "wall", "wall", "wall", "gte1", "gte1", "wall", "wall", "wall", "wall", "wall", "gte1", "gte1", "wall", "wall", "wall", "wall", "wall"],
    ["wall", "roid", "bos2", "bos2", "bos2", "bos2", "bos2", "roid", "wall", "port", "port", "port", "port", "port", "port", "port", "wall", "nest", "nest", "nest", "nest", "nest", "nest", "wall"],
    ["wall", "bos2", "bos2", "bos2", "bos2", "bos2", "bos2", "bos2", "wall", "port", "port", "port", "port", "port", "port", "port", "wall", "nest", "nest", "nest", "nest", "nest", "nest", "wall"],
    ["wall", "bos2", "bos2", "bos2", "roid", "bos2", "bos2", "bos2", "wall", "port", "port", "port", "port", "port", "port", "port", "wall", "nest", "nest", "nest", "nest", "nest", "nest", "wall"],
    ["wall", "bos2", "roid", "bos2", "bos2", "bos2", "bos2", "bos2", "wall", "port", "port", "port", "port", "port", "port", "port", "wall", "nest", "nest", "nest", "nest", "nest", "nest", "wall"],
    ["wall", "bos2", "bos2", "bos2", "bos2", "bos2", "bos2", "bos2", "wall", "port", "port", "port", "port", "port", "port", "port", "wall", "nest", "nest", "nest", "nest", "nest", "nest", "wall"],
    ["wall", "roid", "bos2", "roid", "bos2", "bos2", "roid", "bos2", "wall", "port", "port", "port", "port", "port", "port", "port", "wall", "nest", "nest", "nest", "nest", "nest", "nest", "wall"],
    ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"]
],
  "FOOD_AMOUNT": 1,
  "BOTS": 10, 
  "PLAYER_SPAWN_LOCATION": "spw1",
  "TEAMS": [1],
  "BOT_SPAWN_LOCATION": "norm",
  "BOT_TEAMS": [2],
  "SANCTUARIES": true,
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": true,
  "SPAWN_CRASHER": true,
  "SPAWN_SENTINEL": true,
  "SPAWN_FALLEN_BOSSES": true,
  "SPAWN_PENTAGON_SENTINELS": true,
  "SPAWN_FALLEN_ENEMIES": true,
}
