module.exports =
{
  "WIDTH": 4000,
  "HEIGHT": 4000,
  "MODE": "kingOfHill",
  "RANDOM_COLORS": true,
  "ALLOW_SERVER_END": true,
"ROOM_SETUP": [
["rock", "wall", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "roid"],
["norm", "norm", "norm", "norm", "wall", "norm", "rock", "norm", "roid", "wall", "norm", "wall", "wall", "norm", "norm"],
["norm", "norm", "norm", "roid", "wall", "norm", "norm", "norm", "wall", "wall", "norm", "wall", "rock", "norm", "wall"],
["wall", "norm", "norm", "wall", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm"],
["wall", "roid", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "wall", "norm", "norm", "norm", "wall", "norm"],
["wall", "norm", "norm", "rock", "norm", "wall", "wall", "nest", "wall", "wall", "norm", "roid", "wall", "norm", "wall"],
["norm", "norm", "wall", "wall", "wall", "wall", "nest", "nest", "nest", "wall", "norm", "norm", "norm", "norm", "norm"],
["wall", "norm", "roid", "norm", "norm", "nest", "nest", "dom0", "nest", "nest", "norm", "wall", "rock", "norm", "wall"],
["rock", "norm", "norm", "wall", "norm", "wall", "nest", "nest", "nest", "wall", "norm", "wall", "norm", "wall", "wall"],
["norm", "norm", "norm", "wall", "norm", "wall", "wall", "nest", "wall", "wall", "norm", "norm", "norm", "norm", "roid"],
["norm", "wall", "roid", "norm", "norm", "norm", "norm", "norm", "wall", "roid", "norm", "norm", "wall", "wall", "norm"],
["norm", "wall", "wall", "norm", "norm", "wall", "norm", "norm", "wall", "norm", "norm", "roid", "norm", "wall", "norm"],
["norm", "wall", "norm", "norm", "rock", "norm", "wall", "roid", "norm", "norm", "wall", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "wall", "norm", "norm", "wall", "wall", "norm", "norm", "norm", "wall", "norm", "norm", "roid"],
["rock", "norm", "norm", "wall", "norm", "norm", "roid", "norm", "norm", "wall", "norm", "wall", "norm", "norm", "wall"]
],
  "FOOD_AMOUNT": 0.5,
  "BOTS": 10,
  "TEAMS": "color",
  "BOT_TEAMS": "color",
  "SANCTUARIES": true,
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": true,
}
