
module.exports =

{
  "WIDTH": 4000,
  "HEIGHT": 4000,
  
  "MODE": "graveyard",
  "ALLOW_SERVER_END": true, 
"ROOM_SETUP": [ 
   ["norm", "norm", "norm", "norm", "wall", "wall", "norm", "norm", "wall", "norm", "rock", "norm","norm", "norm", "norm", "norm", "bas1", "bas1", "bas1"],
   ["norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "roid","wall", "norm", "wall", "norm", "bas1", "bap1", "bas1"],
   ["norm", "norm", "norm", "roid", "norm", "norm", "wall", "norm", "norm", "wall", "norm", "norm","norm", "rock", "norm", "roid", "bas1", "bas1", "bas1"],
   ["norm", "norm", "norm", "rock", "wall", "norm", "norm", "rock", "wall", "norm", "rock", "wall","wall", "norm", "roid", "rock", "norm", "norm", "norm"],
   ["wall", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "norm","wall", "rock", "wall"],
   ["norm", "norm", "wall", "wall", "wall", "wall", "norm", "wall", "rock", "norm", "roid", "wall", "norm", "norm", "wall", "wall","norm", "norm", "norm"],
   ["wall", "norm", "norm", "norm", "norm", "roid", "nest", "nest", "wall", "nest", "nest", "nest", "wall", "norm", "norm", "norm","norm", "norm", "rock"],
   ["roid", "wall", "norm", "wall", "wall", "norm", "nest", "nest", "nest", "nest", "nest", "wall", "nest", "norm", "wall", "norm","wall", "norm", "norm"],
   ["rock", "norm", "norm", "rock", "norm", "wall", "nest", "wall", "wall", "nest", "wall", "nest", "nest", "wall", "norm", "wall","norm", "wall", "norm"],
   ["norm", "wall", "wall", "norm", "norm", "norm", "wall", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["wall", "roid", "norm", "norm", "rock", "norm", "nest", "nest", "wall", "nest", "wall", "nest", "wall", "norm", "wall", "wall", "rock","rock", "norm"],
   ["norm", "norm", "wall", "wall", "norm", "rock", "nest", "wall", "nest", "nest", "wall", "nest", "nest", "norm", "norm", "norm","norm", "norm", "wall"],
   ["wall", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "wall", "nest", "wall", "wall", "norm", "norm", "norm", "norm"],
   ["norm", "roid", "wall", "norm", "wall", "wall", "rock", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid","rock", "norm", "wall"],
   ["norm", "norm", "norm", "norm", "norm", "wall", "norm", "roid", "rock", "norm", "norm", "roid", "norm", "wall", "wall", "norm","norm", "wall", "norm"],
   ["norm", "norm", "roid", "rock", "norm", "norm", "norm", "rock", "norm", "roid", "rock", "norm", "roid", "norm", "rock", "roid","norm", "norm", "norm"],
   ["bas3", "bas3", "bas3", "roid", "wall", "norm", "rock", "norm", "wall", "rock", "norm", "norm", "norm", "wall", "norm", "norm","bas4", "bas4", "bas4"],
   ["bas3", "bap3", "bas3", "norm", "norm", "roid", "norm", "rock", "norm", "norm", "norm", "rock","rock", "norm", "norm", "norm", "bas4", "bap4", "bas4"],
   ["bas3", "bas3", "bas3", "norm", "norm", "wall", "norm", "roid", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "norm","bas4", "bas4", "bas4"]
  ],
  "DAMAGE_CONSTANT": 0.6, 
  "KNOCKBACK_CONSTANT": 1,  
  "ROOM_BOUND_FORCE": 0.01,
  "FOOD": [
    100, 
    34,
    17,
    10,
    1,
    0.1,
    0.01,
    0.001,
  ],
  "FOOD_NEST": [
    0.1, 
    0.1,
    0.1,
    100,
    10,
    1,
    0.1,
    0.01,
  ],
  "SKILL_CAP": 45,
  "FOOD_AMOUNT": 1,
  "BOTS": 10,
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [1, 3, 4],
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [1, 3, 4],
  "BASE_DRONES": true,
  "PLAGUE": true,
  "SPAWN_FOOD": true,
  "SPAWN_NEUTRAL_BOSSES": true,
  "SPAWN_CRASHER": true,
  "SPAWN_SENTINEL": true,
  "SPAWN_FALLEN_BOSSES": true,
}
