module.exports =
{
  "WIDTH": 6000,
  "HEIGHT": 6000,
  "MODE": "mazeDomination",
"ROOM_SETUP":[
    ["bas2", "bas2", "bas2", "wall", "norm", "wall", "norm", "wall", "norm", "wall", "wall", "norm", "norm", "norm", "wall", "wall", "norm", "wall", "norm", "wall", "norm", "wall", "bas1", "bas1", "bas1"],
    ["bas2", "bap2", "bas2", "norm", "norm", "wall", "norm", "wall", "norm", "norm", "wall", "wall", "norm", "wall", "wall", "norm", "norm", "wall", "norm", "wall", "norm", "norm", "bas1", "bap1", "bas1"],
    ["bas2", "bas2", "bas2", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "bas1", "bas1", "bas1"],
    ["wall", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "wall"],
    ["norm", "norm", "norm", "wall", "wall", "norm", "wall", "wall", "wall", "norm", "wall", "wall", "norm", "wall", "wall", "norm", "wall", "wall", "wall", "norm", "wall", "wall", "norm", "norm", "norm"],
    ["wall", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "wall", "wall"],
    ["norm", "norm", "norm", "norm", "wall", "wall", "wall", "norm", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "wall", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "norm"],
    ["wall", "wall", "wall", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "wall", "wall", "wall"],
    ["norm", "norm", "norm", "norm", "wall", "norm", "wall", "norm", "dom0", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "dom0", "norm", "wall", "norm", "wall", "norm", "norm", "norm", "norm"],
    ["wall", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "wall", "wall", "wall", "wall", "norm", "wall", "wall", "wall", "wall", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "wall"],
    ["wall", "wall", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "wall", "nest", "nest", "nest", "nest", "nest", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "wall", "wall"],
    ["norm", "wall", "wall", "norm", "wall", "wall", "norm", "wall", "norm", "wall", "nest", "nest", "nest", "nest", "nest", "wall", "norm", "wall", "norm", "wall", "wall", "norm", "wall", "wall", "norm"],
    ["norm", "norm", "wall", "norm", "norm", "wall", "norm", "wall", "norm", "norm", "nest", "nest", "dom0", "nest", "nest", "norm", "norm", "wall", "norm", "wall", "norm", "norm", "wall", "norm", "norm"],
    ["norm", "wall", "wall", "norm", "wall", "wall", "norm", "wall", "norm", "wall", "nest", "nest", "nest", "nest", "nest", "wall", "norm", "wall", "norm", "wall", "wall", "norm", "wall", "wall", "norm"],
    ["wall", "wall", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "wall", "nest", "nest", "nest", "nest", "nest", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "wall", "wall"],
    ["wall", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "wall", "wall", "wall", "wall", "norm", "wall", "wall", "wall", "wall", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "wall"],
    ["norm", "norm", "norm", "norm", "wall", "norm", "wall", "norm", "dom0", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "dom0", "norm", "wall", "norm", "wall", "norm", "norm", "norm", "norm"],
    ["wall", "wall", "wall", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "wall", "wall", "wall"],
    ["norm", "norm", "norm", "norm", "wall", "wall", "wall", "norm", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "wall", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "norm"],
    ["wall", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "wall", "wall"],
    ["norm", "norm", "norm", "wall", "wall", "norm", "wall", "wall", "wall", "norm", "wall", "wall", "norm", "wall", "wall", "norm", "wall", "wall", "wall", "norm", "wall", "wall", "norm", "norm", "norm"],
    ["wall", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "wall"],
    ["bas3", "bas3", "bas3", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "bas4", "bas4", "bas4"],
    ["bas3", "bap3", "bas3", "norm", "norm", "wall", "norm", "wall", "norm", "norm", "wall", "wall", "norm", "wall", "wall", "norm", "norm", "wall", "norm", "wall", "norm", "norm", "bas4", "bap4", "bas4"],
    ["bas3", "bas3", "bas3", "wall", "norm", "wall", "norm", "wall", "norm", "wall", "wall", "norm", "norm", "norm", "wall", "wall", "norm", "wall", "norm", "wall", "norm", "wall", "bas4", "bas4", "bas4"]
],
  "BOTS": 16,
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [1, 2, 3, 4],
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [1, 2, 3, 4],
  "DOMINATION": true,
  "DOMINATOR_COUNT": 3,
  "SPAWN_FOOD": true,
  "SPAWN_NEUTRAL_BOSSES": true, 
  "SPAWN_CRASHER": true,
  "SPAWN_SENTINEL": true,
}
