module.exports =
{
  "WIDTH": 4000,
  "HEIGHT": 4000,
  "MODE": "domination",
"ROOM_SETUP": [
  ["bas2", "bas2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bas1", "bas1"],
["bas2", "bap2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bap1", "bas1"],
["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "dom0", "roid", "rock", "rock", "roid", "dom0", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "roid", "nest", "nest", "nest", "nest", "roid", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "rock", "nest", "nest", "nest", "nest", "rock", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "rock", "nest", "nest", "nest", "nest", "rock", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "roid", "nest", "nest", "nest", "nest", "roid", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "dom0", "roid", "rock", "rock", "roid", "dom0", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
["bas3", "bap3", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bap4", "bas4"],
["bas3", "bas3", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bas4", "bas4"],
  ],
  "DAMAGE_CONSTANT": 0.6, 
  "KNOCKBACK_CONSTANT": 1,  
  "ROOM_BOUND_FORCE": 0.01,
  "FOOD": [
    100, 
    34,
    17,
    10,
    1,
    0.1,
    0.01,
    0.001,
  ],
  "FOOD_NEST": [
    0.1, 
    0.1,
    0.1,
    100,
    10,
    1,
    0.1,
    0.01,
  ],
  "SKILL_CAP": 45,
  "FOOD_AMOUNT": 1,
  "BOTS": 10,
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [1, 2, 3, 4],
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [1, 2, 3, 4],
  "BASE_DRONES": false,
  "SANCTUARIES": false,
  "PLAGUE": false, 
  "GROWTH": false,
  "POLY_ATTACK": false,
  "SHINY_GLORY": false,
  "SOCCER": false,
  "SIEGE": false,
  "DOMINATION": true,
  "DOMINATOR_COUNT": 3,
  "SPAWN_FOOD": true,
  "SPAWN_NEUTRAL_BOSSES": true,
  "SPAWN_CRASHER": true,
  "SPAWN_SENTINEL": true,
  "SPAWN_GUARDIAN_BOSSES": false,
  "SPAWN_FALLEN_BOSSES": false,
  "SPAWN_PENTAGON_SENTINELS": false,
  "SPAWN_VOIDLORD_ENEMIES": false,
  "SPAWN_VOIDLORD_BOSSES_AND_ENEMIES": false,
  "INSTANT_CAPTURE": false,
  "SPAWN_DESCENDED_ENEMIES": false,
  "SPAWN_SPARKS": false,
  "TESTBED_ACCESS": 1,
  "ACTIVATION_MODE": "normal"
}
