module.exports =
{
  "WIDTH": 4000,
  "HEIGHT": 4000,
  "MODE": "plague",
  "RANDOM_COLORS": true,
  "ALLOW_SERVER_END": true,
"ROOM_SETUP": [
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm","norm", "norm", "norm", "norm", "norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid","norm", "norm", "norm", "norm", "norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm","norm", "rock", "norm", "norm", "norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "rock", "norm","norm", "norm", "roid", "norm", "norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "norm","norm", "rock", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "roid", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "roid", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "rock"],
   ["roid", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["rock", "norm", "norm", "rock", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "roid", "norm", "norm", "rock", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "rock","rock", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "rock", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
   ["norm", "roid", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid","rock", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid", "rock", "norm", "norm", "roid", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "roid", "rock", "norm", "roid", "norm", "rock", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm", "rock", "norm", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "roid", "norm", "rock", "norm", "norm", "norm", "rock","rock", "norm", "norm", "norm", "norm", "norm", "norm"],
   ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm","norm", "norm", "norm"]
  ],
  "FOOD_AMOUNT": 0.75,
  "TEAMS": "color",
  "BOTS": 10,
  "BOT_TEAMS": "color",
  "SPAWN_FOOD": true,
  "SPAWN_NEUTRAL_BOSSES": true,
  "SPAWN_CRASHER": true,
  "SPAWN_SENTINEL": true,
}
