module.exports =
{
  //"gameSpeed": 1.5,
  "WIDTH": 3500,
  "HEIGHT": 3500,
  "MODE": "siege",
  "ROOM_SETUP": [
  
["spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0"],
["spw0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "spw0"],
["spw0", "norm", "norm", "norm", "norm", "norm", "dom1", "norm", "norm", "norm", "norm", "norm", "spw0"],
["spw0", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "spw0"],
["spw0", "norm", "norm", "nest", "frt1", "frt1", "gte1", "frt1", "frt1", "nest", "norm", "norm", "spw0"],
["spw0", "norm", "norm", "nest", "frt1", "nest", "nest", "nest", "frt1", "nest", "norm", "norm", "spw0"],
["spw0", "norm", "dom1", "nest", "gte1", "nest", "dom1", "nest", "gte1", "nest", "dom1", "norm", "spw0"],
["spw0", "norm", "norm", "nest", "frt1", "nest", "nest", "nest", "frt1", "nest", "norm", "norm", "spw0"],
["spw0", "norm", "norm", "nest", "frt1", "frt1", "gte1", "frt1", "frt1", "nest", "norm", "norm", "spw0"],
["spw0", "norm", "norm", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "norm", "norm", "spw0"],
["spw0", "norm", "norm", "norm", "norm", "norm", "dom1", "norm", "norm", "norm", "norm", "norm", "spw0"],
["spw0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "spw0"],
["spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0", "spw0"],
    ],
  "BOTS": 0,
  "PLAYER_SPAWN_LOCATION": "dom",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [1],
  "BOT_SPAWN_LOCATION": "dom",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [1], 
  "SANCTUARIES": true,
  "SIEGE": true,
  "DOMINATION": true,
  "DOMINATOR_COUNT": 5,
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false,
  "SPAWN_GUARDIAN_BOSSES": false,
}
