module.exports =
{
  "WIDTH": 5000,
  "HEIGHT": 5000,
  "MODE": "theDistance",
  "DISABLED_TEAM_MESSAGE": true,
  "INSTANT_CAPTURE": true,
  "ROOM_SETUP": [ 
    ["bdrR", "bdrR", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD"],
    ["bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "wall", "wall", "wall", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "tmpl", "pth4", "fcD3", "norm", "norm", "bstR", "norm", "bstU", "norm", "bstR", "bas1", "bstS", "norm", "norm", "rock", "norm", "pth1", "tmpl", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "fcR3", "pth4", "pth4", "norm", "nest", "bstR", "norm", "norm", "norm", "bstR", "bas1", "bstS", "gggo", "norm", "norm", "norm", "pth1", "fcL3", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "norm", "norm", "norm", "fcL3", "bstR", "norm", "bstD", "norm", "bstR", "bas1", "bstS", "norm", "norm", "norm", "roid", "pth1", "norm", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "norm", "norm", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "wall", "wall", "wall", "bdrU", "bdrU", "bdrR", "norm", "norm", "norm", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "wall", "bstL", "bstU", "bstD", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "bdrR", "norm", "rock", "roid", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "rock", "norm", "rock", "bdrL", "wall", "wall", "wall", "wall", "bdrU", "wall", "bdrU", "wall", "wall", "wall", "bdrR", "norm", "norm", "norm", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "rock", "norm", "rock", "bdrL", "wall", "wall", "wall", "wall", "bdrU", "wall", "bdrU", "wall", "wall", "wall", "bdrR", "norm", "norm", "norm", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "wall", "norm", "wall", "bdrL", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "bdrR", "roid", "norm", "norm", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "norm", "norm", "bdrL", "wall", "wall", "wall", "bdrU", "wall", "wall", "wall", "bdrU", "wall", "wall", "bdrR", "rock", "norm", "rock", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "rock", "wall", "norm", "bdrL", "wall", "wall", "wall", "wall", "bdrL", "bdrU", "bdrR", "wall", "wall", "wall", "bdrR", "roid", "norm", "roid", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "norm", "norm", "bdrL", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "bdrR", "roid", "norm", "roid", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "wall", "norm", "wall", "bdrL", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "bdrR", "roid", "norm", "roid", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "norm", "norm", "bdrL", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "bdrR", "norm", "bstD", "norm", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "wall", "norm", "bdrL", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "bdrR", "norm", "norm", "norm", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "norm", "norm", "bdrL", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "bdrD", "norm", "norm", "roid", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "norm", "norm", "norm", "norm", "norm", "bstD", "bstL", "roid", "roid", "roid", "roid", "rock", "norm", "norm", "norm", "norm", "norm", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "norm", "norm", "norm", "norm", "norm", "norm", "bstL", "norm", "norm", "bstL", "norm", "norm", "norm", "norm", "norm", "pth2", "pth2", "pth2", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "tmpl", "norm", "norm", "norm", "norm", "norm", "bstU", "bstL", "roid", "roid", "roid", "roid", "rock", "norm", "norm", "norm", "fcU3", "tmpl", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrR", "bdrR", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrL", "bdrL", "bdrL"],
    ["bdrR", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU", "bdrU"]
],
  "ROOM_BOUND_FORCE": 0.1,
  "FOOD_AMOUNT": 5,
  "BOTS": 4,
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [1],
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [1],
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false
}
