module.exports =
{
  "WIDTH": 5000,
  "HEIGHT": 5000,
  "MODE": "theAwakening",
  "DISABLED_TEAM_MESSAGE": true,
  "INSTANT_CAPTURE": true,
  "DEADLY_BORDERS": true,
  ROOM_SETUP: [
    ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"],
    ["wall", "roid", "zne7", "zne7", "zne7", "wall", "norm", "wall", "norm", "cse1", "wall", "wall", "wall", "cse5", "norm", "wall", "zne9", "wall", "zne6", "zne6", "zne6", "zne6", "wall"],
    ["wall", "zne7", "zne7", "roid", "zne7", "wall", "norm", "wall", "norm", "norm", "cse2", "wall", "cse4", "norm", "norm", "wall", "zne9", "wall", "zne6", "roid", "zne6", "roid", "wall"],
    ["wall", "zne7", "roid", "zne7", "roid", "wall", "roid", "wall", "wall", "hmmm", "norm", "cse3", "norm", "norm", "wall", "wall", "zne9", "wall", "roid", "zne6", "zne6", "zne6", "wall"],
    ["wall", "zne7", "bos7", "roid", "zne7", "wall", "zne9", "zne9", "wall", "wall", "norm", "norm", "norm", "wall", "wall", "zne9", "zne9", "wall", "zne6", "zne6", "gard", "bos6", "wall"],
    ["wall", "zne7", "zne7", "gard", "zne7", "zne7", "zne9", "roid", "roid", "wall", "wall", "gte5", "wall", "wall", "zne9", "zne9", "zne9", "zne6", "zne6", "zne6", "roid", "zne6", "wall"],
    ["wall", "roid", "gard", "zne7", "zne7", "wall", "roid", "zne9", "zne9", "zne9", "zne9", "rep11", "zne9", "zne9", "zne9", "roid", "zne9", "wall", "zne6", "zne6", "zne6", "roid", "wall"],
    ["wall", "wall", "zne7", "wall", "zne7", "wall", "zne9", "zne9", "zne9", "zne9", "zne9", "gard", "zne9", "zne9", "zne9", "zne9", "zne9", "wall", "zne6", "wall", "zne6", "wall", "wall"],
    ["wall", "wall", "swch", "wall", "zne7", "wall", "zne9", "zne9", "gard", "nest", "roid", "nest", "zne9", "nest", "gard", "zne9", "roid", "wall", "zne6", "wall", "swch", "wall", "wall"],
    ["wall", "wall", "wall", "wall", "wall", "wall", "zne9", "zne9", "zne9", "roid", "zne9", "zne9", "zne9", "roid", "zne9", "zne9", "zne9", "wall", "wall", "wall", "wall", "wall", "wall"],
    ["wall", "zne1", "zne1", "zne1", "zne1", "wall", "roid", "zne9", "roid", "gard", "zne9", "bos9", "zne9", "gard", "roid", "zne9", "zne9", "wall", "zne2", "zne2", "roid", "zne2", "wall"],
    ["wall", "roid", "gard", "zne1", "roid", "wall", "zne9", "zne9", "zne9", "zne9", "zne9", "gard", "zne9", "zne9", "zne9", "zne9", "zne9", "wall", "zne2", "zne2", "gard", "gard", "wall"],
    ["wall", "bos1", "zne1", "zne1", "zne1", "wall", "zne9", "zne9", "gard", "roid", "zne9", "roid", "roid", "zne9", "gard", "zne9", "zne9", "wall", "roid", "zne2", "bos2", "roid", "wall"],
    ["wall", "gard", "zne1", "zne1", "zne1", "wall", "wall", "roid", "zne9", "zne9", "zne9", "roid", "zne9", "zne9", "zne9", "zne9", "wall", "wall", "zne2", "zne2", "zne2", "zne2", "wall"],
    ["wall", "wall", "wall", "wall", "zne1", "zne1", "wall", "wall", "zne9", "zne9", "zne9", "zne9", "zne9", "zne9", "zne9", "wall", "wall", "zne2", "zne2", "wall", "wall", "wall", "wall"],
    ["edge", "edge", "edge", "wall", "wall", "zne1", "zne1", "wall", "wall", "gard", "zne9", "zne9", "zne9", "gard", "wall", "wall", "zne2", "zne2", "wall", "wall", "edge", "edge", "edge"],
    ["edge", "edge", "edge", "edge", "wall", "wall", "zne1", "zne1", "wall", "wall", "gard", "zne9", "gard", "wall", "wall", "zne2", "zne2", "wall", "wall", "edge", "edge", "edge", "edge"],
    ["edge", "edge", "edge", "edge", "edge", "wall", "wall", "zne1", "zne1", "wall", "wall", "gte5", "wall", "wall", "zne2", "zne2", "wall", "wall", "edge", "edge", "edge", "edge", "edge"],
    ["edge", "edge", "edge", "edge", "edge", "edge", "wall", "wall", "zne1", "zne1", "norm", "rep5", "norm", "zne2", "zne2", "wall", "wall", "edge", "edge", "edge", "edge", "edge", "edge"],
    ["edge", "edge", "edge", "edge", "edge", "edge", "edge", "wall", "wall", "wall", "norm", "norm", "norm", "wall", "wall", "wall", "edge", "edge", "edge", "edge", "edge", "edge", "edge"],
    ["edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "wall", "norm", "norm", "norm", "wall", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge"],
    ["edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "wall", "bas0", "bas0", "bas0", "wall", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge"],
    ["edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "wall", "wall", "wall", "wall", "wall", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge"]
],

  "TEAMS": [100],
  "FOOD_AMOUNT": 5, 
  "BOTS": 5,
  "PLAYER_SPAWN_LOCATION": "bas0",
  "BOT_SPAWN_LOCATION": "bas0",
  "BOT_TEAMS": [100],
  "BASE_DRONES": true,
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false,
  "SPAWN_SPECIAL_ENEMIES": true,
}