module.exports =
{
  "WIDTH": 7000,
  "HEIGHT": 3500,
  "MODE": "theGreatPlague",
  "DISABLED_TEAM_MESSAGE": true,
  "INSTANT_CAPTURE": true,
  "ROOM_SETUP": [
   ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall"],
   ["wall", "vpr2", "norm", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "paf0", "fta0","paf0", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "fta0","nest", "nest", "nest", "nest", "wall", "wall", "wall"],
   ["wall", "norm", "norm", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "norm", "norm","norm", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "nest","nest", "nest", "nest", "nest", "nest", "wall", "wall"],
   ["wall", "norm", "norm", "wall", "wall", "wall", "norm", "norm", "wall", "wall", "norm", "norm","norm", "norm", "norm", "wall", "wall", "wall", "wall", "wall", "nest", "nest", "nest", "nest", "wall", "wall", "wall", "wall", "wall", "nest", "nest","nest", "paf0", "wall", "nest", "nest", "wall", "wall"],
   ["wall", "norm", "norm", "wall", "wall", "norm", "norm", "norm", "norm", "wall", "wrkb", "norm","norm", "fta0", "norm", "wall", "wall", "wall", "wall", "nest", "nest", "nest", "nest", "nest", "wall", "wall", "wall", "wall", "nest", "nest", "nest","nest", "wall", "paf0", "nest", "nest", "norm", "wall"],
   ["wall", "wall", "gte0", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "norm","norm", "fta0", "norm", "wall", "dom0", "wall", "wall", "nest", "nest", "nest", "paf0", "nest", "wall", "wall", "wall", "wall", "gte0", "gte0", "nest","nest", "nest", "nest", "nest", "norm", "norm", "wall"],
   ["wall", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "norm","norm", "fta0", "norm", "gte0", "dom0", "gte0", "wall", "nest", "nest", "nest", "nest", "nest", "wall", "wall", "wall", "wall", "gte0", "gte0", "nest","wall", "wall", "nest", "wall", "paf0", "norm", "wall"],
   ["wall", "wall", "norm", "norm", "gte0", "norm", "norm", "norm", "norm", "wall", "paf0", "fta0","paf0", "wall", "norm", "norm", "fta0", "norm", "fta0", "gte0", "gte0", "fta0", "nest", "nest", "nest", "wall", "wall", "wall", "nest", "nest", "nest","fta0", "wall", "wall", "wall", "wall", "norm", "wall"],
   ["wall", "wall", "norm", "norm", "wall", "wall", "wall", "norm", "norm", "wall", "wall", "wall","wall", "wall", "wall", "norm", "wall", "norm", "wall", "nest", "nest", "wall", "nest", "nest", "nest", "gte0", "norm", "fta0", "nest", "nest", "nest","nest", "norm", "norm", "norm", "wall", "norm", "wall"],
   ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "dom0", "norm", "wall", "wall", "wall","wall", "wall", "wall", "gte0", "wall", "gte0", "wall", "gte0", "gte0", "wall", "wall", "nest", "nest", "fta0", "norm", "wall", "norm", "nest", "nest","nest", "norm", "norm", "wall", "paf0", "norm", "wall"],
   ["wall", "norm", "gte0", "norm", "norm", "wall", "norm", "norm", "wall", "wall", "wall", "nest","nest", "nest", "nest", "norm", "wall", "norm", "wall", "nest", "nest", "wall", "wall", "fta0", "nest", "fta0", "norm", "wall", "wall", "wall", "nest","nest", "norm", "norm", "wall", "norm", "norm", "wall"],
   ["wall", "norm", "gte0", "norm", "norm", "wall", "norm", "norm", "wall", "wall", "nest", "nest","nest", "dom0", "nest", "norm", "wall", "norm", "wall", "wall", "bos2", "norm", "wall", "wall", "nest", "gte0", "norm", "norm", "norm", "wall", "nest","nest", "norm", "norm", "wall", "dom0", "norm", "wall"],
   ["wall", "norm", "gte0", "norm", "norm", "norm", "norm", "bos0", "bos0", "wall", "nest", "nest","nest", "nest", "nest", "wall", "wall", "norm", "norm", "wall", "wall", "norm", "norm", "wall", "nest", "norm", "norm", "fta0", "norm", "wall", "wall","norm", "bos3", "wall", "wall", "norm", "dom0", "wall"],
   ["wall", "dom0", "wall", "dom0", "norm", "norm", "norm", "bos0", "bos0", "wall", "nest", "fta0","nest", "nest", "nest", "wall", "norm", "norm", "norm", "nest", "wall", "bos2", "norm", "wall", "nest", "norm", "norm", "wall", "norm", "norm", "wall","norm", "norm", "wall", "norm", "norm", "norm", "wall"],
   ["wall", "norm", "fta0", "norm", "norm", "norm", "bos0", "wall", "wall", "paf0", "nest", "nest","nest", "nest", "wall", "norm", "bos2", "norm", "nest", "nest", "wall", "wall", "gte0", "wall", "wall", "norm", "norm", "wall", "norm", "norm", "wall","wall", "norm", "wall", "norm", "norm", "norm", "wall"],
   ["wall", "norm", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "norm", "nest", "nest","nest", "wall", "wall", "bos2", "fta0", "norm", "nest", "nest", "nest", "nest", "nest", "wall", "wall", "norm", "norm", "wall", "norm", "norm", "norm","norm", "norm", "wall", "nest", "nest", "nest", "wall"],
   ["wall", "bos1", "norm", "bos1", "bos1", "fta0", "gte0", "norm", "gte0", "norm", "nest", "nest","wall", "wall", "wall", "bos2", "nest", "nest", "nest", "fta0", "norm", "fta0", "nest", "nest", "wall", "wall", "norm", "wall", "wall", "norm", "norm","norm", "wall", "wall", "nest", "prf0", "nest", "wall"],
   ["wall", "bos1", "bos1", "bos1", "bos1", "norm", "gte0", "norm", "wall", "wall", "wall", "wall","wall", "wall", "wall", "fta0", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "wall", "norm", "wall", "wall", "norm", "norm","norm", "wall", "norm", "nest", "nest", "nest", "wall"],
   ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall"]
  ],
  "FOOD_AMOUNT": 0.25,
  "PLAYER_SPAWN_LOCATION": "vpr",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [2],
  "BOT_SPAWN_LOCATION": "norm",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [100], 
  "SIEGE": true,
  "DOMINATION": true,
  "DOMINATOR_COUNT": 8,
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false
}
