module.exports =
 
{
  "WIDTH": 4000,
  "HEIGHT": 4000,
  "MODE": "theControlled",
  "DISABLED_TEAM_MESSAGE": true,
  "INSTANT_CAPTURE": true,
  "DEADLY_BORDERS": true,
"ROOM_SETUP": [
   ["edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge","edge", "edge", "edge"],
   ["edge", "wall", "wall", "wall", "wall", "wall", "wall", "edge", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall"],
   ["edge", "wall", "wall", "wall", "wall", "norm", "wall", "wall", "wall", "wall", "norm", "wall","wall", "ftD3", "norm", "norm", "wall", "wall", "wall"],
   ["wall", "wall", "ftD3", "wall", "vpr4", "norm", "wall", "bos2", "vpr4", "norm", "norm", "gte3","rep2", "dom3", "norm", "norm", "norm", "bas4", "vpr4"],
   ["wall", "ftR3", "dom3", "wall", "norm", "wall", "wall", "wall", "norm", "norm", "norm", "wall", "wall", "ftU3", "wall", "norm","wall", "bas4", "wall"],
   ["wall", "wall", "fcR3", "vpr4", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "wall", "wall", "wall", "wall", "fcU3","wall", "bas4", "wall"],
   ["edge", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "norm", "wall", "norm", "fao3", "ftD3", "wall","wall", "wall", "wall"],
   ["edge", "wall", "norm", "norm", "fao3", "norm", "norm", "wall", "bad4", "wall", "norm", "wall", "vpr4", "bos0", "lab3", "lab3","lab3", "wall", "wall"],
   ["edge", "wall", "vpr4", "bos3", "norm", "norm", "norm", "gte3", "rep3", "vpr4", "fcU3", "wall", "bos5", "lab3", "ftU3", "wall","lab3", "wall", "wall"],
   ["edge", "wall", "wall", "wall", "wall", "norm", "wall", "wall", "wall", "wall", "wall", "fao3", "fcU3", "wall", "wall", "wall","lab3", "wall", "edge"],
   ["edge", "wall", "norm", "dom3", "norm", "norm", "wall", "fcD3", "norm", "wall", "wall", "wall", "dom3", "ftL3", "wall", "wall", "lab3","wall", "edge"],
   ["wall", "wall", "norm", "vpr4", "wall", "fcU3", "wall", "norm", "norm", "norm", "norm", "wall", "wall", "wall", "wall", "norm","norm", "wall", "edge"],
   ["wall", "ftR3", "norm", "ftU3", "wall", "wall", "wall", "norm", "wall", "wall", "wall", "wall", "fcD3", "wall", "fcD3", "norm", "wall", "wall","edge"],
   ["wall", "wall", "norm", "wall", "norm", "norm", "norm", "norm", "norm", "fcD3", "wall", "wall", "norm", "norm", "norm", "norm","fcL3", "wall", "edge"],
   ["edge", "wall", "norm", "wall", "norm", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "fcL3","bos4", "wall", "edge"],
   ["edge", "wall", "fcU3", "wall", "gte3", "wall", "wall", "norm", "norm", "norm", "vpr4", "fao3", "norm", "fao3", "norm", "fao3","vpr4", "wall", "edge"],
   ["edge", "wall", "norm", "norm", "rep4", "wall", "wall", "fcU3", "fcU3", "wall", "spw4", "wall", "wall", "wall", "wall", "wall","norm", "wall", "edge"],
   ["edge", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "edge"],
   ["edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge", "edge","edge", "edge", "edge"]
  ],  
  "TEAMS": [4],
  "FOOD_AMOUNT": 6,
  "BOTS": 10,
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "BOT_SPAWN_LOCATION": "norm",
  "BOT_TEAMS": [3],
  "BASE_DRONES": true,
  "SANCTUARIES": true,
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false
}