module.exports =
{
  "WIDTH": 8000,
  "HEIGHT": 2000,
  "MODE": "theInfestation",
  "DEADLY_BORDERS": true, 
  "DISABLED_TEAM_MESSAGE": true,
  "INSTANT_CAPTURE": true,
  "ROOM_SETUP": [
["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "frt0", "frt0", "norm", "norm", "norm", "norm", "norm", "norm", "tmpl", "norm", "norm", "norm", "norm", "norm", "frt0", "frt0", "frt0", "frt0", "norm", "norm", "norm", "tmpl", "norm", "norm", "frt0", "frt0", "frt0", "norm", "norm", "norm", "norm", "frt0", "tmpl", "frt0", "fao0", "gte0", "gte0", "gte0", "norm", "norm", "fao0", "frt0", "frt0", "frt0", "frt0", "frt0", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "frt0", "frt0", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "frt0", "ftD0", "frt0", "roid", "norm", "norm", "roid", "norm", "norm", "norm", "frt0", "frt0", "frt0", "norm", "norm", "norm", "norm", "frt0", "frt0", "ftD0", "norm", "gte0", "dom0", "gte0", "norm", "roid", "norm", "frt0", "fao0", "ftD0", "fao0", "frt0", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "frt0", "frt0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "gte0", "gte0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "frt0", "nest", "norm", "norm", "norm", "norm", "gte0", "norm", "gte0", "norm", "fao0", "frt0", "frt0", "norm", "norm", "norm", "frt0", "norm", "gte0", "norm", "frt0", "wall"],
["wall", "bas2", "bas2", "roid", "norm", "ftD0", "ftD0", "bos0", "norm", "norm", "roid", "norm", "roid", "norm", "norm", "norm", "roid", "norm", "norm", "frt0", "frt0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bos1", "nest", "frt0", "nest", "bos1", "norm", "norm", "roid", "gte0", "norm", "gte0", "norm", "ftD0", "frt0", "frt0", "norm", "norm", "norm", "gte0", "norm", "gte0", "norm", "frt0", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "gte0", "gte0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "gte0", "gte0", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "norm", "gte0", "gte0", "gte0", "norm", "norm", "roid", "norm", "gte0", "norm", "gte0", "norm", "gte0", "gte0", "gte0", "norm", "norm", "norm", "gte0", "nest", "gte0", "nest", "dom0", "wall"],
["vpr2", "dbc2", "bas2", "norm", "norm", "gte0", "dom0", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "gte0", "dom0", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "bos1", "gte0", "dom0", "gte0", "bos1", "norm", "norm", "norm", "gte0", "norm", "gte0", "norm", "gte0", "dom0", "gte0", "bos2", "roid", "norm", "gte0", "nest", "gte0", "nest", "vpr0", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "gte0", "gte0", "norm", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "roid", "norm", "norm", "gte0", "gte0", "norm", "roid", "norm", "norm", "norm", "roid", "norm", "norm", "gte0", "gte0", "gte0", "norm", "norm", "norm", "norm", "gte0", "norm", "gte0", "norm", "gte0", "gte0", "gte0", "norm", "norm", "roid", "gte0", "nest", "gte0", "nest", "dom0", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "ftU0", "ftU0", "bos0", "norm", "roid", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "frt0", "frt0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bos1", "nest", "frt0", "nest", "bos1", "norm", "norm", "norm", "gte0", "norm", "gte0", "norm", "ftU0", "frt0", "frt0", "norm", "norm", "norm", "gte0", "norm", "gte0", "norm", "frt0", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "frt0", "frt0", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "norm", "norm", "gte0", "gte0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "frt0", "nest", "norm", "norm", "norm", "roid", "gte0", "norm", "gte0", "norm", "fao0", "frt0", "frt0", "norm", "roid", "roid", "frt0", "norm", "gte0", "norm", "frt0", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "frt0", "frt0", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "frt0", "ftU0", "frt0", "roid", "norm", "roid", "norm", "norm", "norm", "norm", "frt0", "frt0", "frt0", "norm", "norm", "roid", "norm", "frt0", "frt0", "ftU0", "norm", "gte0", "dom0", "gte0", "norm", "norm", "norm", "frt0", "fao0", "ftU0", "fao0", "frt0", "wall"],
["wall", "bas2", "bas2", "norm", "norm", "frt0", "frt0", "norm", "norm", "norm", "norm", "roid", "norm", "tmpl", "norm", "norm", "norm", "norm", "norm", "frt0", "frt0", "frt0", "frt0", "norm", "norm", "norm", "tmpl", "norm", "norm", "frt0", "frt0", "frt0", "norm", "norm", "norm", "norm", "frt0", "tmpl", "frt0", "fao0", "gte0", "gte0", "gte0", "norm", "norm", "fao0", "frt0", "frt0", "frt0", "frt0", "frt0", "wall"],
["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"],
  ],
  "ROOM_BOUND_FORCE": 1,
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "TEAMS": [2],
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [2],
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false,
  "SIEGE": true
}
