module.exports =

{
  "WIDTH": 4000,
  "HEIGHT": 4000,
  "MODE": "theExpanse",
  "DISABLED_TEAM_MESSAGE": true,
  "INSTANT_CAPTURE": true,
  "DEADLY_BORDERS": true,
"ROOM_SETUP": [
   ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall"],
   ["wall", "norm", "norm", "none", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "none","wall", "norm", "norm", "norm", "norm", "bas3", "wall"],
   ["wall", "wall", "wall", "norm", "norm", "wall", "none", "norm", "norm", "none", "wall", "norm","norm", "norm", "wall", "wall", "norm", "bas3", "wall"],
   ["wall", "norm", "norm", "norm", "wall", "wall", "norm", "wall", "wall", "none", "none", "wall","wall", "wall", "wall", "wall", "wall", "wall", "wall"],
   ["wall", "zne0", "wall", "none", "wall", "none", "norm", "norm", "norm", "wall", "wall", "norm", "none", "norm", "none", "gte3","dbc3", "wall", "wall"],
   ["wall", "zne0", "wall", "wall", "wall", "wall", "wall", "wall", "norm", "wall", "norm", "wall", "norm", "norm", "wall", "wall","gte4", "wall", "wall"],
   ["wall", "zne0", "zne0", "zne0", "zne0", "wall", "wall", "norm", "wall", "norm", "norm", "nest", "wall", "norm", "wall", "zne2","rep3", "zne2", "wall"],
   ["wall", "zne0", "zne0", "zne0", "zne0", "wall", "wall", "norm", "norm", "norm", "norm", "wall", "none", "none", "wall", "zne2","zne2", "zne2", "wall"],
   ["wall", "zne0", "zne0", "zne0", "zne0", "wall", "none", "wall", "wall", "none", "none", "none", "none", "wall", "zne2", "zne2","bos2", "zne2", "wall"],
   ["wall", "zne0", "bos0", "zne0", "zne0", "wall", "none", "norm", "wall", "none", "bos3", "none", "wall", "zne2", "zne2", "zne2","zne2", "zne2", "wall"],
   ["wall", "rep1", "wall", "wall", "wall", "wall", "none", "wall", "wall", "none", "none", "none", "wall", "zne2", "zne2", "zne2", "zne2","zne2", "wall"],
   ["wall", "gte4", "wall", "wall", "zne1", "wall", "zne1", "wall", "norm", "wall", "wall", "wall", "zne2", "zne2", "zne2", "zne2","wall", "zne2", "wall"],
   ["wall", "bad3", "wall", "zne1", "zne1", "zne1", "zne1", "wall", "norm", "norm", "norm", "wall", "wall", "zne2", "wall", "wall", "zne2", "zne2","wall"],
   ["wall", "gte3", "wall", "zne1", "wall", "zne1", "wall", "wall", "wall", "wall", "norm", "norm", "norm", "wall", "norm", "none","wall", "zne2", "wall"],
   ["wall", "norm", "wall", "zne1", "zne1", "zne1", "rep2", "gte4", "spw3", "gte3", "norm", "norm", "none", "wall", "wall", "norm","none", "norm", "wall"],
   ["wall", "norm", "zne1", "zne1", "zne1", "zne1", "zne1", "wall", "wall", "wall", "wall", "norm", "wall", "norm", "wall", "norm","wall", "norm", "wall"],
   ["wall", "none", "wall", "zne1", "zne1", "bos1", "zne1", "wall", "wall", "none", "wall", "norm", "none", "norm", "norm", "norm","norm", "none", "wall"],
   ["wall", "none", "wall", "zne1", "zne1", "zne1", "zne1", "wall", "wall", "norm", "norm", "norm","norm", "norm", "norm", "norm", "norm", "norm", "wall"],
   ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall","wall", "wall", "wall"]
  ], 
  "TEAMS": [3],
  "FOOD_AMOUNT": 20, 
  "BOTS": 5,
  "PLAYER_SPAWN_LOCATION": "bas",
  "CONSIDER_PLAYER_TEAM_LOCATION": true,
  "BOT_SPAWN_LOCATION": "bas",
  "CONSIDER_BOT_TEAM_LOCATION": true,
  "BOT_TEAMS": [3],
  "BASE_DRONES": true,
  "SPAWN_FOOD": false,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false,
  "SPAWN_VOIDLORD_ENEMIES": true
}