module.exports =
{
  "WIDTH": 2500,
  "HEIGHT": 2500,
  "MODE": "theDenied",
  "DISABLED_TEAM_MESSAGE": true,
  "INSTANT_CAPTURE": true,
 "ROOM_SETUP": [
   ["bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0"],
   ["bas0", "norm", "norm", "norm", "wall", "norm", "rock", "norm", "roid", "wall", "rock", "wall", "wall", "norm", "wall", "bas0"],
   ["bas0", "roid", "gte1", "roid", "wall", "rock", "norm", "norm", "wall", "wall", "rock", "wall", "norm", "gte1", "norm", "bas0"],
   ["bas0", "norm", "norm", "wall", "rock", "norm", "wall", "norm", "norm", "norm", "norm", "wall", "norm", "norm", "norm", "bas0"],
   ["bas0", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "wall", "none", "norm", "norm", "wall", "roid", "bas0"],
   ["bas0", "norm", "norm", "norm", "norm", "wall", "wall", "nest", "wall", "wall", "roid", "roid", "wall", "norm", "wall", "bas0"],
   ["bas0", "bad1", "tst4", "wall", "wall", "wall", "wal0", "wal0", "wal0", "wall", "norm", "norm", "norm", "rock", "norm", "bas0"],
   ["bas0", "norm", "norm", "norm", "norm", "nest", "wal0", "spw0", "wal0", "nest", "norm", "wall", "rock", "norm", "norm", "bas0"],
   ["bas0", "norm", "norm", "wall", "norm", "wall", "wal0", "wal0", "wal0", "wall", "rock", "wall", "rock", "wall", "norm", "bas0"],
   ["bas0", "norm", "norm", "wall", "norm", "wall", "wall", "nest", "wall", "rock", "rock", "norm", "norm", "roid", "norm", "bas0"],
   ["bas0", "wall", "roid", "norm", "norm", "norm", "norm", "norm", "rock", "roid", "norm", "norm", "wall", "wall", "norm", "bas0"],
   ["bas0", "wall", "wall", "norm", "norm", "wall", "norm", "norm", "wall", "norm", "norm", "roid", "norm", "wall", "roid", "bas0"],
   ["bas0", "wall", "norm", "none", "rock", "norm", "wall", "roid", "norm", "norm", "wall", "norm", "norm", "norm", "norm", "bas0"],
   ["bas0", "norm", "gte1", "wall", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "norm", "gte1", "wall", "bas0"],
   ["bas0", "norm", "norm", "wall", "norm", "norm", "roid", "tmpl", "norm", "wall", "norm", "wall", "norm", "norm", "norm", "bas0"],
   ["bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0", "bas0"]
   ],
  "FOOD_NEST": [
    0.1, 
    0.1,
    0.1,
    100,
    20,
    10,
    1,
    0.2,
  ],
  "FOOD_AMOUNT": 0.34,
  "PLAYER_SPAWN_LOCATION": "random",
  "TEAMS": [1],
  "BOT_TEAMS": [100],
  "SPAWN_FOOD": true,
  "SPAWN_NEUTRAL_BOSSES": false,
  "SPAWN_CRASHER": false,
  "SPAWN_SENTINEL": false
}
