module.exports = 
{    
  "gameSpeed": 1, 
  "WIDTH": 8000,     
  "HEIGHT": 8000,      
  "MODE": "ffa",
  "RANDOM_COLORS": false,
"ROOM_SETUP":[
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"]
],
  DEADLY_BORDERS: false,
   ALLOW_SERVER_END: false,
  "ENCLOSED_ARENA": false,
  "DISABLED_TEAM_MESSAGE": false,
  "MAZE_GENERATION": false,
  "DAMAGE_CONSTANT": 0.6, 
  "KNOCKBACK_CONSTANT": 1,  
  "ROOM_BOUND_FORCE": 0.01,
  "FOOD": [
    100, 
    34,
    17,
    10,
    1,
    0.1,
    0.01,
    0.001,
  ],
  "FOOD_NEST": [
    0.1, 
    0.1,
    0.1,
    100,
    10,
    1,
    0.1,
    0.01,
  ],
  "SKILL_CAP": 45,
  "MAX_SKILL": 9,
   "SOFT_MAX_SKILL": 0.59,
  "SKILL_SOFT_CAP": 0,
  "SKILL_CHEAT_CAP": 45,
  "SKILL_LEAK": 0,
  "SKILL_BOOST": 5,
  "FOOD_AMOUNT": 0.25, 
  "BOTS": 0,
  "TEAMS": [1, 2, 3, 4],
  "PLAYER_SPAWN_LOCATION": "random",
  "CONSIDER_PLAYER_TEAM_LOCATION": false,
  "CONSIDER_BOT_TEAM_LOCATION": false,
  "BOT_SPAWN_LOCATION": "norm",
  "BOT_TEAMS": [1, 2, 3, 4],
  "BASE_DRONES": false,
  "SANCTUARIES": false, 
  "PLAGUE": false, 
  "GROWTH": false,
  "POLY_ATTACK": false,
  "SHINY_GLORY": false,
  "SOCCER": false,  
  "SIEGE": false,
  "DOMINATION": false,
  "DOMINATOR_COUNT": 4,
  INSTANT_CAPTURE: false,
  "SPAWN_FOOD": true,
  "SPAWN_NEUTRAL_BOSSES": true,
  ENEMY_INTENSITY: {
    CRASHERS: 25,
    THRASHERS: 15,
    SENTINELS: 5,
    },
  BOSS_LIMIT: {
    GUARDIANS: 3,
    FALLEN: 3,
    HIGHLORDS: 3,
    VOIDLORDS: 3,
   NEUTRAL_ALLIANCE: 3,
    },
    "NETWORK_UPDATE_FACTOR": 24,
  "SOCKET_WARNING_LIMIT": 5,
  "NETWORK_FRONTLOG": 1,
  "NETWORK_FALLBACK_TIME": 30,
  "VISIBLE_LIST_INTERVAL": 750,
  "RUN_SPEED": 1.5,
  "MAX_HEARTBEAT_INTERVAL": 30000000,
  "VERBOSE": true,
  "BANNED_CHARACTER_REGEX": "/[\\uFDFD\\u200E\\u0000]/gi",
  "STEALTH": 4,
  "MIN_SPEED": 0.001,

  "TIER_1": 15,
  "TIER_2": 30,
  "TIER_3": 45,
  "TIER_4": 75,
  "TIER_5": 125,
  "TIER_6": 150,
  "TIER_7": 200,
  "TIER_8": 250,
  "TIER_9": 300,
  "TIER_10": 350,
  "TIER_11": 400,
  "TIER_12": 450,
  "TIER_13": 550,
  "TIER_14": 600,
  "TIER_15": 650,
  "TIER_GOD": 1000,

  "GLASS_HEALTH_FACTOR": 3.6,
  "RESPAWN_TIMER": 5,
  "STARTING_CLASS": "basic",
  "SPAWN_CRASHER": true,
  "SPAWN_SENTINEL": true,
  "SPAWN_GUARDIAN_BOSSES": false,
  "SPAWN_FALLEN_BOSSES": false,
  "SPAWN_VOIDLORD_ENEMIES": false,
  "REDUCE_BOTS_PER_PLAYER": 1,
  "ACTIVATION_MODE": "normal"
}
